### ISSUE TITLE
Question -  Volume Up and Down

### ISSUE THREAD

**Issue by jyanes83** [christianhaitian/Retro-CM3#2]
Hey Buddy - love what you have done.   I can not find good documentation from the original maker or seem to get any of the instructions online around setting hotkeys to control volume up and down on the device.   Since there is no dedicated analog audio control.

Is there a way to do this?

**Comment by christianhaitian** [comment]
The document [here](https://github.com/christianhaitian/Retro-CM3/raw/master/Retro-CM3%20User%20manual%20-%20%E5%89%AF%E6%9C%AC.docx) is the last instructions that was available for the retrocm3.  By default, volume control is available using select+up and down on the dpad.  It only works for retroarch based emulators as well.
