### ISSUE TITLE
WIFI Issue - Failed to Raise Network Interfaces .. no WLAN0 detected

### ISSUE THREAD

**Issue by jyanes83** [christianhaitian/Retro-CM3#3]
Hello -  I flashed your latest image for the retro-cm3.  However I can not get WIFI to work.  

During Boot I can see an error stating "Failed to raise network interfaces...."

Once booted and in Retropie configuration, it will say that no WLAN0 is detected.  

 I noticed you made some tweaks to the Realtek driver.   Any thoughts?   I was going to try and download the image prior to this version but that link no longer seems to work.  

Appreciate the help.

**Comment by christianhaitian** [comment]
Did you turn on your wireless adapter following the instructions here?  https://github.com/christianhaitian/Retro-CM3/raw/master/Retro-CM3%20User%20manual%20-%20%E5%89%AF%E6%9C%AC.docx

**Comment by jyanes83** [comment]
I'm an idiot.  Sorry.  That worked.  Did you see that instruction to double tap the power.  Thanks 

⁣--Jonathan Yanes ​
