### ISSUE TITLE
Donwload link dead

### ISSUE THREAD

**Issue by Fil923** [christianhaitian/Retro-CM3#4]
Hello,
this link for downloading image is dead: https://mega.nz/#!6Exx3KxQ!_lUvmDBmij-S-CCtFUOg16-os0f4tB3Wc76pQxuvMwo

could you please update? Thanks

**Comment by christianhaitian** [comment]
It still works on my end.

**Comment by Fil923** [comment]
Strange! maybe i'm blind! 👯 
Thanks mate!
