### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by TheMediocritist** [christianhaitian/Retro-CM3#5]
Hello,

I messed up the SD card my Retro CM3 came with and have not been able to repair it. The official build boots but buttons are unresponsive. Your build seems to be my only hope, but unfortunately the mega links don’t work. If you could re-upload or point me in the right direction I will be forever grateful!

**Comment by christianhaitian** [comment]
Link has been updated.  Thanks for bringing this to my attention. https://mega.nz/#!6Exx3KxQ!_lUvmDBmij-S-CCtFUOg16-os0f4tB3Wc76pQxuvMwo
